### ISSUE TITLE
Empty rp2paths results

### ISSUE THREAD

**Issue by Melclic** [brsynth/rp2paths#4]
Running the following RetroPath2.0 results, 
[rp_pathways_28.csv.zip](https://github.com/brsynth/rp2paths/files/4981653/rp_pathways_28.csv.zip)
 returns empty out_path.csv results. Ran using the following conditions: 

**Molecule Name:** Hydrocodone
**Molecule InChI:** InChI=1S/C18H21NO3/c1-19-8-7-18-11-4-5-13(20)17(18)22-16-14(21-2)6-3-10(15(16)18)9-12(11)19/h3,6,11-12,17H,4-5,7-9H2,1-2H3/t11-,12+,17-,18-/m0/s1
**GEM SBML:** s_cerevisiae_iMM904.sbml
**TopX:** 1000
**Max Steps:** 14
**Rule Diameters:** 2,4,6,8,10,12,14,16

**Comment by tduigou** [comment]
Thanks @Melclic. That is due to the default value of the `--maxsteps` argument. Until now, the default was 10, which means that only pathway having between 1 and 10 steps are outputted, pathways having more steps were filtered. Starting from the now the default value will be 0 for 'unlimited' number of steps, meaning no pathway filtering based on this criteria anymore.
